# Generated by Django 3.1.6 on 2021-02-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='dummy_url'),
            preserve_default=False,
        ),
    ]
